### ISSUE TITLE
The split of training set and validating set

### ISSUE THREAD

**Issue by songw-zju** [morancyc/USNet#1]
Hi, thank you for your great work! Could I know how do you split the KITTI-Road dataset in the ablation study? Thanks in advance.

**Comment by morancyc** [comment]
Thanks for attention. In the ablation study of our work, we split the training set into two subsets: 253 samples for training and 36 samples for validating. The validating part consists of the last 12 images of 'uu','umm' and 'um' category. And you can split the training and validating set by yourself in your work.

**Comment by songw-zju** [comment]
Thanks a lot for your help!
