### ISSUE TITLE
Mismatch in Image Resize Dimensions

### ISSUE THREAD

**Issue by Geekgineer** [morancyc/USNet#5]
#### Issue:
While trying to utilize the `transform_tr` function for image preprocessing of the KITTI dataset code you have provided, I noticed a potential mismatch in the order of the resizing dimensions. The width and height appear to be inverted between the definition and the actual implementation.

crop_height = 384,  #help='Height of cropped/resized input image to network')
crop_width  = 1248, #help='Width of cropped/resized input image to network')

#### Details:
In the function definition:
```python
def transform_tr(self, sample):
    ...
    tr.Resize(size=(self.args.crop_width, self.args.crop_height)),
    ...
```
The resizing dimensions are passed as (width, height).

However, in the Resize class, which implements the transformation:

```python
class Resize(object):
    def __init__(self, size):
        self.size = size    # size: (h, w)
    ...
```

The comment suggests that the expected format is (height, width).

This inversion means that the image will be resized to a width of 384 and a height of 1248, contrary to the intended dimensions.

When the resize operation is called in the Resize class's __call__ method, it will actually resize the image to have width of 384 and height of 1248, which is inverted from what you'd expect based on the transform_tr method.

Am I missing something here?

**Comment by morancyc** [comment]
Thank you for your correction.  The expected order of the parameter 'size' is (width, height), while the comment in the Resize class was wrong, and we have corrected it in the new commit.

**Comment by Geekgineer** [comment]
Thank you for the response and the swift hot fix. 
Regards.
